# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Prince

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

stages:
- task: UiPathPack@2
  stageName: Pack
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: $(projectPath)
    outputType: 'Process'
    orchestratorConnection: 'ConnectFin'
    outputPath: $(projectPackagePath)

- task: UiPathDeploy@2
  stage: Deploy
  inputs:
    orchestratorConnection: 'ConnectFin'
    packagesPath: '$(projectPackagePath)'
    folderName: 'Shared'
    entryPoints: 'Main.xaml'
    traceLevel: 'Verbose'

- task: UiPathRunJob@2
  stage: Run
  dependsOn:Deploy
  condition:succeededOrFailed()
  inputs:
    orchestratorConnection: 'ConnectFin'
    processName: 'cicdpipeline'
    folderName: 'Shared'
    user: 'desktop-4m969hi\prince'
    machine: 'local machines'
    resultFilePath: '$(projectPackagePath)'
    traceLevel: 'Verbose'
